#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

# Determine which docker compose command is available
if command -v docker compose &> /dev/null; then
  compose_cmd="docker compose"
elif command -v docker-compose &> /dev/null; then
  compose_cmd="docker-compose"
else
  echo "Neither 'docker compose' nor 'docker-compose' is installed." >&2
  exit 1
fi

while :; do
  case $1 in
    -d|--detached)
      detached="true"
      ;;
    -v|--verbose)
      verbose="true"
      ;;
    *)
      break
  esac

  shift
done


if [ "${detached}" = "true" ]; then
  $compose_cmd up -d &&
    npm run start:detached
elif [ "${verbose}" = "true" ]; then
  $compose_cmdup -d &&
    npm run start:verbose
else
  $compose_cmd up -d &&
    npm run start
fi
